/**
 * Drizzle schema — single source of truth for the PostgreSQL schema.
 *
 * Module-specific tables are declared in `<module>/infrastructure/db/*.schema.ts`
 * and re-exported from this barrel so drizzle-kit picks them up from one path.
 */

export {
  rolesTable,
  usuariosTable,
  type RoleRow,
  type NewRoleRow,
  type UsuarioRow,
  type NewUsuarioRow
} from "../../../../modules/usuarios-roles/infrastructure/db/usuarios-roles.schema.js";

export {
  estadoSolicitudEnum,
  estadoConfirmacionEnum,
  estadoLineaDistribucionEnum,
  tipusProveedorEnum,
  autorHistorialEnum,
  parteConfirmacionEnum,
  prosegurImportStatusEnum,
  prosegurEntryStatusEnum,
  caDestinosTable,
  caMaterialesTable,
  caProveedoresTable,
  caAsignacionesTable,
  caSolicitudesTable,
  caLineasSolicitudTable,
  caHistorialSolicitudTable,
  caLineasDistribucionTable,
  caConfirmacionesTable,
  caEntradasRealesTable,
  caProsegurImportsTable,
  caProsegurEntriesTable,
  caProsegurMaterialMapTable,
  caHorarioLlegadasTable,
  caHorarioPlantillaTable,
  type CaDestinoRow,
  type NewCaDestinoRow,
  type CaMaterialRow,
  type NewCaMaterialRow,
  type CaProveedorRow,
  type NewCaProveedorRow,
  type CaAsignacionRow,
  type NewCaAsignacionRow,
  type CaSolicitudRow,
  type NewCaSolicitudRow,
  type CaLineaSolicitudRow,
  type NewCaLineaSolicitudRow,
  type CaHistorialSolicitudRow,
  type NewCaHistorialSolicitudRow,
  type CaLineaDistribucionRow,
  type NewCaLineaDistribucionRow,
  type CaConfirmacionRow,
  type NewCaConfirmacionRow,
  type CaEntradaRealRow,
  type NewCaEntradaRealRow,
  type CaProsegurImportRow,
  type NewCaProsegurImportRow,
  type CaProsegurEntryRow,
  type NewCaProsegurEntryRow,
  type CaProsegurMaterialMapRow,
  type NewCaProsegurMaterialMapRow,
  type CaHorarioLlegadaRow,
  type NewCaHorarioLlegadaRow,
  type CaHorarioPlantillaRow,
  type NewCaHorarioPlantillaRow,
} from "../../../../modules/combustibles/infrastructure/db/combustibles.schema.js";
